//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TablaTrabajos
    {
        public int Id { get; set; }
        public string TituloTrabajo { get; set; }
        public string Ubicacion { get; set; }
        public double Salario { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public bool Estado { get; set; }
        public int TipoContratoId { get; set; }
        public int CategoriaTrabajoId { get; set; }
    
        public virtual CategoriasTrabajos CategoriasTrabajos { get; set; }
        public virtual TipoContratoes TipoContratoes { get; set; }
    }
}
